import './globals.css'
import { Inter } from 'next/font/google'
import Sidebar from './Sidebar'
import Header from './Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Scrapommerce',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex bg-white">

        {/*sidebar*/}
        <Sidebar/>
        <main className="bg-white">
          <Header/>
        {children}

        </main>
        </body>
    </html>
  )
}
